
export enum Gender {
  MASCULINE = "MASCULINE",
  FEMININE = "FEMININE",
  NEUTER = "NEUTER"
}

export enum Case {
  NOMINATIVE = "NOMINATIVE",
  ACCUSATIVE = "ACCUSATIVE",
  DATIVE = "DATIVE",
  GENITIVE = "GENITIVE"
}

export enum Number {
  SINGULAR = "SINGULAR",
  PLURAL = "PLURAL"
}

export enum DeterminerType {
  DEFINITE_ARTICLE = "DEFINITE ARTICLE",
  INDEFINITE_ARTICLE = "INDEFINITE ARTICLE",
  NEGATIVE_ARTICLE = "NEGATIVE ARTICLE",
  POSSESSIVE_DETERMINER = "POSSESSIVE DETERMINER",
  DIESER_DETERMINER = "DIESER DETERMINER",
  ALLE_DETERMINER = "ALLE DETERMINER",
  BEIDE_DETERMINER = "BEIDE DETERMINER",
  EINIGE_DETERMINER = "EINIGE DETERMINER",
  JEDER_DETERMINER = "JEDER DETERMINER",
  JENER_DETERMINER = "JENER DETERMINER",
  MANCHER_DETERMINER = "MANCHER DETERMINER",
  MEHRERE_DETERMINER = "MEHRERE DETERMINER",
  SAEMTLICH_DETERMINER = "SAEMTLICH DETERMINER",
  VIELE_DETERMINER = "VIELE DETERMINER",
  WELCHER_DETERMINER = "WELCHER DETERMINER",
  WENIGE_DETERMINER = "WENIGE DETERMINER",
  EIN_PAAR_DETERMINER = "EIN PAAR DETERMINER",
  IRGENDEIN_DETERMINER = "IRGENDEIN DETERMINER",
  IRGENDWELCHE_DETERMINER = "IRGENDWELCHER DETERMINER",
  WAS_FUER_DETERMINER = "WAS FUER DETERMINER"
}

export enum Person {
  FIRST_PERSON = "FIRST PERSON",
  SECOND_PERSON = "SECOND PERSON",
  THIRD_PERSON = "THIRD PERSON"
}

export enum PronounType {
  PERSONAL_PRONOUN = "PERSONAL PRONOUN",
  PREPOSITIONAL_ADVERB = "PREPOSITIONAL ADVERB",
  REFLEXIVE_PRONOUN = "REFLEXIVE PRONOUN",
  DEMONSTRATIVE_PRONOUN = "DEMONSTRATIVE PRONOUN",
  POSSESSIVE_PRONOUN = "POSSESSIVE PRONOUN",
  EINER_PRONOUN = "EINER PRONOUN",
  KEINER_PRONOUN = "KEINER PRONOUN",
  ETWAS_PRONOUN = "ETWAS PRONOUN",
  JEMAND_PRONOUN = "JEMAND PRONOUN",
  NICHTS_PRONOUN = "NICTS PRONOUN",
  NIEMAND_PRONOUN = "NIEMAND PRONOUN",
  WAS_PRONOUN = "WAS PRONOUN",
  WELCHER_PRONOUN = "WELCHER PROUNOUN",
  WER_PRONOUN = "WER PROUNOUN"
}
