export enum PronounType {
  PERSONAL_PRONOUN = "PERSONAL PRONOUN",
  PREPOSITIONAL_ADVERB = "PREPOSITIONAL ADVERB",
  REFLEXIVE_PRONOUN = "REFLEXIVE PRONOUN",
  DEMONSTRATIVE_PRONOUN = "DEMONSTRATIVE PRONOUN",
  POSSESSIVE_PRONOUN = "POSSESSIVE PRONOUN",
  EINER_PRONOUN = "EINER PRONOUN",
  KEINER_PRONOUN = "KEINER PRONOUN",
  ETWAS_PRONOUN = "ETWAS PRONOUN",
  JEMAND_PRONOUN = "JEMAND PRONOUN",
  NICHTS_PRONOUN = "NICTS PRONOUN",
  NIEMAND_PRONOUN = "NIEMAND PRONOUN",
  WAS_PRONOUN = "WAS PRONOUN",
  WELCHER_PRONOUN = "WELCHER PROUNOUN",
  WER_PRONOUN = "WER PROUNOUN"
}
